# Assingment 2
# NAME: Tushar Kuradia
# Reg. No: 24-27-28
# Programme Name: M.Tech Data Science

In [65]:
# a)

import numpy as np
var1 = np.arange(0, 31)
print(var1)
var1.shape

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30]


(31,)

In [12]:
# b.)
"""Since var1 has 31 elements and 31 can't be converted into 2D.
So removing the first element to make it 30"""

var1 = np.delete(var1, 0)
var2 = var1.reshape(5, 6)
print(var2)
var2.shape

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]


(5, 6)

In [14]:
# c)

var3 = var1.reshape(2, 5, 3)
print(var3)
var3.shape

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]
  [13 14 15]]

 [[16 17 18]
  [19 20 21]
  [22 23 24]
  [25 26 27]
  [28 29 30]]]


(2, 5, 3)

In [16]:
# d)

var2[1][0] = -1
print(f"Var 2: \n{var2} \n Var 1: \n{var1} \n Var 3: \n{var3}")
print("Since we used reshape on var1 to get var2 and var3 it creates a copy of the numpy array. So we can conclude that if the elements of an array is modified then the other generated arrays' elements will also be modified. ")

Var 2: 
[[ 1  2  3  4  5  6]
 [-1  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]] 
 Var 1: 
[ 1  2  3  4  5  6 -1  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30] 
 Var 3: 
[[[ 1  2  3]
  [ 4  5  6]
  [-1  8  9]
  [10 11 12]
  [13 14 15]]

 [[16 17 18]
  [19 20 21]
  [22 23 24]
  [25 26 27]
  [28 29 30]]]
Since we used reshape on var1 to get var2 and var3 it creates a copy of the numpy array. So we can conclude that if the elements of an array is modified then the other generated arrays' elements will also be modified. 


In [18]:
# e)

# i)
res1 = np.sum(var3, axis = 1)
print("Sum over 2nd Dimension: \n", res1)

# ii)
res2 = np.sum(var3, axis = 2)
print("\nSum over 3rd Dimension: \n", res2)

# iii)
res3 = np.sum(var3, axis = (0, 2))
print("\nSum over 1st and 3rd Dimensions: \n", res3)

Sum over 2nd Dimension: 
 [[ 27  40  45]
 [110 115 120]]

Sum over 3rd Dimension: 
 [[ 6 15 16 33 42]
 [51 60 69 78 87]]

Sum over 1st and 3rd Dimensions: 
 [ 57  75  85 111 129]


In [20]:
# f)

# i)
print("\n2nd Row of var2: \n", var2[1])

# ii)
print("\nLast column of var2: \n", var2[:, -1])

# iii)
print("\nTop Right 2×2 Submatrix of var2: \n", var2[:2, -2:])


2nd Row of var2: 
 [-1  8  9 10 11 12]

Last column of var2: 
 [ 6 12 18 24 30]

Top Right 2×2 Submatrix of var2: 
 [[ 5  6]
 [11 12]]


## Q.2)

In [33]:
# a)

vector = np.arange(10) + 1
print(vector)

[ 1  2  3  4  5  6  7  8  9 10]


In [35]:
# b)

A = vector.reshape(10, 1) + vector
print(A)

[[ 2  3  4  5  6  7  8  9 10 11]
 [ 3  4  5  6  7  8  9 10 11 12]
 [ 4  5  6  7  8  9 10 11 12 13]
 [ 5  6  7  8  9 10 11 12 13 14]
 [ 6  7  8  9 10 11 12 13 14 15]
 [ 7  8  9 10 11 12 13 14 15 16]
 [ 8  9 10 11 12 13 14 15 16 17]
 [ 9 10 11 12 13 14 15 16 17 18]
 [10 11 12 13 14 15 16 17 18 19]
 [11 12 13 14 15 16 17 18 19 20]]


In [37]:
# c)

import numpy.random as npr
data = np.exp(npr.randn(50, 5))

In [39]:
# d)

print(data)

[[ 0.36247236  6.00442974  0.92353169  1.02368067  0.23808164]
 [ 1.57981393  0.52479028  8.97492483  1.10025512  0.74031979]
 [ 0.24551024  0.34695468  0.61558673  0.54227357  0.38516451]
 [ 0.63750235  1.37677547  0.2270466   2.85661156  0.60406213]
 [ 2.44385025  0.67661226  1.19329937  4.85094335  0.79551147]
 [ 0.41953608  3.24973606  1.25730132  1.37647006  1.06515747]
 [ 3.6561251   0.68352163  0.65957433 11.48879393  1.33002752]
 [ 0.18890197  0.66207252  2.77566571  0.18630002  0.41974525]
 [ 2.13603205  0.92566278  0.4368062   0.21712545  2.94099102]
 [ 1.68759723  1.24761084  2.5485176   3.1942714   0.61144593]
 [ 0.21681925  2.56136593  2.36801489  0.41896274  0.49482303]
 [10.25157709  0.87732581  1.29248979  0.40134609  0.39718945]
 [ 0.37618334  0.52137772  1.07006646  0.29159971  0.31417171]
 [ 0.84649694  2.85291251  0.72336246  0.65349078  0.34551675]
 [ 0.28015622  0.18405309  0.82232963  0.54961503  0.45328005]
 [ 0.61184634  1.52282441  6.33844139  0.81742343  0.98

In [41]:
# e)

mean = np.mean(data, axis = 0)
std_dev = np.std(data, axis = 0)
print(f"Mean: {mean}\nStandard Deviation: {std_dev}")

Mean: [1.90317954 1.31239554 1.39891526 2.37148153 1.37778409]
Standard Deviation: [2.31205327 1.26301645 1.53949197 5.27750485 1.52525458]


In [45]:
# f)

normalised = (data - mean)/std_dev
mean = np.mean(normalised, axis = 0)
std_dev = np.std(normalised, axis = 0)
print(f"Mean: {mean}\nStandard Deviation: {std_dev}")

Mean: [1.90317954 1.31239554 1.39891526 2.37148153 1.37778409]
Standard Deviation: [2.31205327 1.26301645 1.53949197 5.27750485 1.52525458]


# Q.2)

In [55]:
# a)

def vandermonde(N):
    vec = np.arange(N) + 1
    return vec[:, np.newaxis] ** (vec - 1)
    
result = vandermonde(12)
print(result)

[[          1           1           1           1           1           1
            1           1           1           1           1           1]
 [          1           2           4           8          16          32
           64         128         256         512        1024        2048]
 [          1           3           9          27          81         243
          729        2187        6561       19683       59049      177147]
 [          1           4          16          64         256        1024
         4096       16384       65536      262144     1048576     4194304]
 [          1           5          25         125         625        3125
        15625       78125      390625     1953125     9765625    48828125]
 [          1           6          36         216        1296        7776
        46656      279936     1679616    10077696    60466176   362797056]
 [          1           7          49         343        2401       16807
       117649      823543     57

In [57]:
# b)

x = np.ones(12)
b = np.dot(result, x)
print(b)

[1.20000000e+01 4.09500000e+03 2.65720000e+05 5.59240500e+06
 6.10351560e+07 4.35356467e+08 2.30688120e+09 1.22713351e+09
 9.43953692e+08 3.73692871e+09 3.10225064e+08 3.10073456e+09]


In [59]:
# c)

from numpy.linalg import inv
result2 = inv(result).dot(b)
print(result2)

[1.00000572 0.99735641 1.00311279 0.999506   1.00002861 0.99999857
 1.0000001  1.         1.         1.         1.         1.        ]


In [61]:
# d)

result3 = np.linalg.solve(result, b)
print(result3)

[1.00000067 0.99999715 1.00000411 0.99999733 1.00000089 0.99999984
 1.00000002 1.         1.         1.         1.         1.        ]
